### PR TITLE
[WIP] addressing option tests

### PR DESCRIPTION
**Pull request by cordoval**
|Q            |A  |
|---          |---|
|Bug Fix?     |n  |
|New Feature? |n  |
|BC Breaks?   |n  |
|Deprecations?|n  |
|Tests Pass?  |n  |
|Fixed Tickets|   |
|License      |MIT|
|Doc PR       |   |
                   

 Sent using [Gush](https://github.com/gushphp/gush)

### CODE REVIEW

**Comment by janschoenherr** [comment]
Hi, could you elaborate on what this change does? Thanks.

**Comment by cordoval** [comment]
this is not finished, i planned to have tests for the options component, however i did not see much activity nor did i have time to finish this. What has happened in pagekit?

**Comment by cordoval** [comment]
closing for now.

**Comment by saschadube** [comment]
Pagekit development is gaining momentum again :smile: See [develop branch](https://github.com/pagekit/pagekit/tree/develop) and [Gitter chat](https://gitter.im/pagekit/pagekit)

**Pull request closed without merging**
