### PR TITLE
Basic memcached support

### PR DESCRIPTION
**Pull request by karevn**
I think memcached support is a must as it is the most mature user data caching system as other ones became obsolete with opcache integration (and it does not support user data). For now, it's a very simple implementation with localhost / standard port support only, but I can create more mature solution.

### CODE REVIEW

**Comment by janschoenherr** [comment]
Hi,

could you remove your decorator changes from this Pull Request? Also, it would be great if you could update your Pull Request to reflect the latest changes in the Pagekit structure. We are in the middle of moving lots of things around - like getting rid of the Service Providers and instead adding Modules. 

Thanks

**Comment by karevn** [comment]
Yep, I am watching your recent changes and already rewrote the cache subsystem using a new architecture (and allowing to add custom cache providers). Do you plan to add any changes to caching module in next few days? I would like to pull a working develop snapshot to test them before pushing.

**Comment by janschoenherr** [comment]
Well, personally I think adding support for them is fine. But I wouldn't, yet, add them to the _settings_ page, but rather make them configurable through the _config.php_ file. Both of them require to connect to a server.

**Comment by karevn** [comment]
I meant the installer extension, not the settings page.

**Comment by janschoenherr** [comment]
Could you elaborate? What's the connection between cache and _installer extension_?

**Comment by karevn** [comment]
Installer UI is a good place to ask user for optional caching service settings which will be then written to config.php. It will lower the learning curve for non-professional users as they will not need to edit the config file.

**Pull request closed without merging**
